server:
  port: 8086
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mgmt
    username: root
    password: QIUHEchamygn1996@
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
logging:
  level:
    org:
      springframework: ERROR